name: Release the api and build notebook

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy_release:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://api-har.martindotpy.dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Config git
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - name: Set up cloudflared
        uses: AnimMouse/setup-cloudflared@v2

      - name: Set up uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      # Notebook build
      - name: Build the notebook
        continue-on-error: true
        run: |
          rm -rf src/assets/notebook

          uv run --no-sync --with nbconvert \
            python -m jupyter nbconvert --to markdown src/har_clustering.ipynb \
            --template-file src/har_clustering.md.j2 \
            --output-dir src/assets/notebook

          git add src/assets/notebook
          git commit -m "feat: Update notebook build"
          git push origin main

      # Deploy
      - name: Deploy in Dokploy
        uses: jmischler72/dokploy-deploy-actions@main
        with:
          PROJECT_NAME: big-data
          APPLICATION_NAME: cliente
          DOKPLOY_HOST: ${{ secrets.DOKPLOY_HOST }}
          DOKPLOY_TOKEN: ${{ secrets.DOKPLOY_TOKEN }}
